const LTDA = Object.freeze({
  VNATOR: 'VNATOR',
  PAGARME: 'PAGAR.ME',
  KOVI: 'KOVI',
  PEDE_PRONTO: 'PEDE_PRONTO',
  CINQ: 'CINQ',
  IESDE: 'IESDE',
  AGROTIS: 'AGROTIS',
  POLVO: 'POLVO',
  FREELANCER: 'FREELANCER',
});

export { LTDA };
